name: Build and Test commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    # We use macos-11 because macos-latest is still 10.15
    runs-on: [ ubuntu-latest ]

    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        
      # Install elan with nightly toolchain
      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:nightly
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          
      - name: build mathlib
        run: lake build
