name: Tactic extraction

on:
  workflow_dispatch:

jobs:
  build:
    name: Extract tactic data
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.6/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          echo | source $HOME/.profile && $HOME/.elan/bin/elan --version

      - uses: actions/checkout@v3

    #  - name: bump toolchain
    #    run: |
    #       curl -O https://raw.githubusercontent.com/leanprover-community/mathlib4/master/lean-toolchain
    #       lake update
    #       git config user.name github-actions
    #       git config user.email github-actions@github.com
    #       git add lean-toolchain lake-manifest.json
    #       git commit -am "Bump `lean-toolchain` to match `Mathlib`"
    #       git push

      - name: fetch cache
        run: lake exe cache get
          
      - name: build LeanInk
        run: lake build

      - name: extract tactic data
        run: |
          python3 tactic_extraction.py
          zip -r tactic_extraction_data.zip TacticExtractionData

      - name: generate tactic census
        run: python3 tactic_census.py

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mathlib-tactic-data
          path: |
            tactic_extraction_data.zip
            tactic_census.json
            error.log
