name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-Ubuntu:
    runs-on: [ ubuntu-latest ]

    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        
      # Install elan with nightly toolchain
      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:nightly -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          
      - name: build LeanInk
        run: lake build
        
  build-macOS:
    # We use macos-11 because macos-latest is still 10.15
    runs-on: [ macos-11 ]

    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        
      # Install elan with nightly toolchain
      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:nightly -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          
      - name: build LeanInk
        run: lake build
        
  build-windows:
    runs-on: [ windows-latest ]

    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        
      # Install elan with nightly toolchain
      - name: install elan
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1
          powershell -f elan-init.ps1 --default-toolchain leanprover/lean4:nightly -y
          del elan-init.ps1
          
      - name: build LeanInk
        run: lake build
